config/routes.rb
Rails.application.routes.draw do
  resources :employees, only: [:update]
  
  get "/employees" => "employees#employees"
  get "/search" => "employees#employees"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   
  root "departments#index"
  get "/employees/new" => "employees#employee_form"
  #post "/employees/create"
  post "/employees/" => "employees#create"
  get "/employee/destroy/:id" => "employees#destroy"
  get "/employee/edit/:id" => "employees#edit"
  
  get "/department/:id" => "departments#department_employees"
  get "/employees/managers" => "employees#managers"
  get "/employees/managers/:id" => "employees#manager_subordinates"
  get "/employees/:id" => "employees#employee_details"
  
  get "/doctors" => "employees#doctors"
  get "/doctors/:id" => "employees#doctor_patients"
  get "/doctors/patients/:id/:did" => "patients#doctor_patient_details" 

  resources :patients
  get "/patient/doctors/:id/:idp" => "employees#doctor_details"
  resources :products
end

app/models/patient.rb
class Patient < ApplicationRecord
  #validates :address, exclusion: { in: %w(delhi gurugram), message: "%{value} is reserved." }
  #validates :address, inclusion: { in: %w(hodal palwal faridabad), message: "not accepting %{value}"}, allow_blank: true #allow_nil: true
  validates :name, length: { minimum: 3 , message: "name should be greater then 3 words"}
  has_many :opd_details
  has_many :employees, through: :opd_details
  #has_one :opd_detail
  #has_and_belongs_to_many :employees
  
  #after_validation :addres_change, if: :address_empty?
  #before_save :check
  #after_save :after_check
  #around_save :around_check
  validate :age_check
  #after_initialize :initialize_obj
  #after_find :find_record
  #after_commit :patient_created
  
  private
  def address_empty?
    if self.address == nil
      return true
    else
      return false
    end
  end

  def addres_change
    self.address = "delhi"
  end
  def check
    self.name.downcase!
  end
  def around_check
    self.name.upcase!
    yield
    puts "new value saved #{self.name}"
  end  
  
  def after_check
    self.name.capitalize!
  end  
  def age_check
    age = ((Time.zone.now - self.dob.to_time) / (1.year.seconds)).to_i
    if age < 8
      self.errors.add :dob, "Patient's age must be greater than 8 year"
    end
  end 
  
  def initialize_obj
    puts "A new object is initailized"
  end  
  def find_record
    puts "#{name} is present in database"
  end
  def patient_created
    puts "patient created successfully"
  end  
end  

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  
  def index 
    @patients = Patient.all
  end  

  def show
    @patient = Patient.find(params[:id])
    @patient_doctors = Patient.find(params[:id]).employees
  end

  def new
    @patient = Patient.new
  end  

  def create
    @patient = Patient.create(patient_params)

    if @patient.save
      redirect_to "/patients/#{@patient.id}"
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end
  
  def update 
    @patient = Patient.find(params[:id])
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end  

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy
    redirect_to patients_url
  end  

  def doctor_patient_details
    @patient = Patient.find(params[:id])
    @did = params[:did]
  end  
  

  private

  def patient_params
    params.require(:patient).permit(:name, :gender, :dob, :address)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<% if @patient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this employee from being saved:</h2>
      <ul>
        <% @patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
 
    </div>
<% end %>

<%= form_for @patient do |form| %>
    
    <div>
      <%= form.label :name  %>
      <%= form.text_field :name %>
    </div><br>
  
    <div>
      <%= form.label :gender  %>
      <%= form.radio_button :gender, "Male" %>
      <%= form.label :Male  %>
      <%= form.radio_button :gender, "Female" %>
      <%= form.label :Female  %>
    </div><br>
  
    <div>
      <%= form.label :dob  %>
      <%= form.date_field :dob %>
    </div><br>
  
    <div>
      <%= form.label :address  %>
      <%= form.text_field :address %>
    </div><br>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/patients/doctor_patient_details.html.erb
<h1>Details Of <%=@patient.name%></h1>
<h3> Id : <%= @patient.id%> </h3>
<h3> Name : <%= @patient.name %></h3>
<h3> Gender : <%= @patient.gender %></h3>
<h3> Date Of Birth : <%= @patient.dob.strftime("%d-%m-%Y") %></h3>
<h3> Addres : <%= @patient.address %></h3> <br>

<%= link_to "previous", "/doctors/#{@did}"%>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Show this patient", @patient %> |
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/index.html.erb
<h1 style="color:green;">List Of All Patients</h1>
<a href="/patients/new">Create New Patient</a>
<ol>
  <% @patients.each do |patient|%>
    <li> <%= link_to patient.name.titleize, "/patients/#{patient.id}" %> 
    &nbsp &nbsp<%= link_to "edit this patient", edit_patient_path(patient) %>
    &nbsp &nbsp <%= button_to "delete this patient", patient_path(patient), method: :delete %>
    </li><br>
  <%end%>  
</ol>

<%=link_to "previous", "/"%>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/show.html.erb
<h1>Details Of <%=@patient.name%></h1>
<h3> Id : <%= @patient.id%> </h3>
<h3> Name : <%= @patient.name %></h3>
<h3> Gender : <%= @patient.gender %></h3>
<h3> Date Of Birth : <%= @patient.dob.strftime("%d-%m-%Y") %></h3>
<h3> Addres : <%= @patient.address %></h3> <br>

<h1>Details Of All Doctors</h1>
<ul>
  <% @patient_doctors.each do |doctor| %>
    <li> <%= link_to doctor.name.titleize, "/patient/doctors/#{doctor.id}/#{@patient.id}" %> </li>
  <%end%>  
</ul>
<%= link_to "previous", "/patients" %>